import copy
numbers = [7, 2, 5]
numbers.append(4)
numbers.insert(1, 10)
numbers.extend([1, 1, 1])
numbers.remove(7)
a = numbers.pop()
numbers = sorted(numbers)
numbers.reverse()
count2 = numbers.count(2)
cnumbers = numbers.copy()
dcnumbers = copy.deepcopy(numbers)
print(numbers)
print(a)
print(count2)
print(numbers.index(1))
numbers = numbers.clear()
print(cnumbers)
print(dcnumbers)
print(numbers)